name: AnalisisGeneral

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analisis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python 3.11.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.8"

    - name: Instalar dependencias
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ejecutar análisis estático (flake8)
      run: |
        pip install flake8
        flake8 .
    - name: Run flake8
      run: flake8
